# Generated by Django 4.1.7 on 2023-03-27 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
